name: build and publish release to Docker Hub

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the tag name
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: checkout code
        uses: actions/checkout@v2

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image and push to Docker Hub
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_USERNAME }}/certbot_dns_duckdns:latest \
            --tag ${{ secrets.DOCKER_USERNAME }}/certbot_dns_duckdns:unstable \
            --tag ${{ secrets.DOCKER_USERNAME }}/certbot_dns_duckdns:${{ steps.get_tag.outputs.TAG }} \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 .
